- name: clone xhprof
  git: repo=https://github.com/phacility/xhprof.git dest=/root/xhprof

- name: install php5-dev
  apt: name=php5-dev state=present
  when: ansible_os_family == 'Debian'

- name: install php-devel
  yum: name=php-devel state=present
  when: ansible_os_family == 'RedHat'

- name: install gcc
  yum: name=gcc state=present
  when: ansible_os_family == 'RedHat'

- name: install gcc
  apt: name=gcc state=present
  when: ansible_os_family == 'Debian'

- name: install php5-curl
  apt: name=php5-curl state=present
  when: ansible_os_family == 'Debian'

- name: build and install xhprof
  shell: cd /root/xhprof/extension && phpize5 && ./configure && make && make install
  when: ansible_os_family == 'Debian'

- name: build and install xhprof
  shell: cd /root/xhprof/extension && phpize && ./configure && make && make install
  when: ansible_os_family == 'RedHat'

- name: put /etc/php5/mods-available/xhprof.ini
  template: src=xhprof.ini dest=/etc/php5/mods-available/xhprof.ini
  when: ansible_os_family == 'Debian'

- name: put /etc/php.d/xhprof.ini
  template: src=xhprof.ini dest=/etc/php.d/xhprof.ini
  when: ansible_os_family == 'RedHat'

- name: clone xhprof.io
  git: repo=https://github.com/staabm/xhprof.io dest={{ xhprof_wwwroot }}/xhprof.io

- name: put config.inc.php
  template: src=config.inc.php dest={{ xhprof_wwwroot }}/xhprof.io/xhprof/includes/config.inc.php
